/**
 * `scripts/build-examples.ts` — regenerates the 12 example files
 * under `examples/` deterministically.
 *
 *   examples/flowchart/flowchart.{svg,html,mermaid}
 *   examples/sequence/sequence.{svg,html,mermaid}
 *   examples/erd/erd.{svg,html,mermaid}
 *   examples/architecture/architecture.{svg,html,mermaid}
 *
 * Each example is a complete end-to-end render via `make_diagram`
 * (parse → layout → render to SVG/Mermaid/HTML). The DSL specs are
 * defined inline below so the build is fully self-contained — no
 * external fixtures, no LLM calls, no I/O outside the `examples/`
 * directory.
 *
 * Determinism: the renderer is pure (see AC-7), the parser is pure
 * (see AC-6), and the layout engine is pure (see AC-12). Two runs
 * of this script on the same source tree produce byte-identical
 * outputs.
 *
 * Usage: `npm run build:examples`  (alias for `tsx scripts/build-examples.ts`)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { __INTERNAL__ as make } from '../src/tools/make-diagram.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EXAMPLES_ROOT = path.resolve(__dirname, '..', 'examples');

interface ExampleSpec {
  /** Directory under `examples/` (also the base name for the 3 files). */
  readonly subdir: 'flowchart' | 'sequence' | 'erd' | 'architecture';
  /** The DSL spec fed to `make_diagram`. */
  readonly spec: string;
  /** The diagram type hint (for `make_diagram`'s `type` arg). */
  readonly type: 'flowchart' | 'sequence' | 'erd';
  /** Theme to render with (every example uses light for byte-stability). */
  readonly theme: 'light';
}

const EXAMPLES: ReadonlyArray<ExampleSpec> = [
  {
    subdir: 'flowchart',
    type: 'flowchart',
    theme: 'light',
    spec: [
      'flowchart: Order processing',
      'A: Start',
      'B [diamond]: Decide',
      'C: Pay',
      'D: Cancel',
      'A -> B',
      'B -> C: yes',
      'B -> D: no',
    ].join('\n'),
  },
  {
    subdir: 'sequence',
    type: 'sequence',
    theme: 'light',
    spec: [
      'sequence: User login',
      'actor U: User',
      'actor S: Application server',
      'actor DB: Database',
      'U -> S: POST /login',
      'S ->> DB: query user',
      'DB --> S: user record',
      'S --> U: 200 OK',
    ].join('\n'),
  },
  {
    subdir: 'erd',
    type: 'erd',
    theme: 'light',
    spec: [
      'erd: Library schema',
      'entity Book: Book { id, title, isbn }',
      'entity Author: Person name { id, name }',
      'entity Publisher: Press name { id, name }',
      'Book ||--o{ Author: written by',
      'Book ||--o{ Publisher: published by',
    ].join('\n'),
  },
  {
    // The self-dogfood example: this is a flowchart of DiagramForge's
    // own pipeline. It is generated by the very pipeline it describes.
    subdir: 'architecture',
    type: 'flowchart',
    theme: 'light',
    spec: [
      'flowchart: DiagramForge pipeline',
      'A: AI agent text spec',
      'B [diamond]: DSL or prose?',
      'C: parse_spec DSL route',
      'D: parse_spec LLM fallback',
      'E: DiagramIR typed',
      'F: render_diagram',
      'G: layout engine',
      'H: SVG output',
      'I: Mermaid output',
      'J: HTML preview',
      'K: theme presets',
      'A -> B: text input',
      'B -> C: DSL',
      'B -> D: prose',
      'C -> E: produces',
      'D -> E: produces',
      'E -> F: typed IR',
      'F -> G: layout pass',
      'F -> H: emit',
      'F -> I: emit',
      'F -> J: emit',
      'K -> F: colors',
    ].join('\n'),
  },
];

async function writeExample(spec: ExampleSpec): Promise<void> {
  const dir = path.join(EXAMPLES_ROOT, spec.subdir);
  mkdirSync(dir, { recursive: true });
  const result = await make.makeImpl({ text: spec.spec, type: spec.type, theme: spec.theme });
  const base = path.join(dir, spec.subdir);
  writeFileSync(`${base}.svg`, result.svg, 'utf8');
  writeFileSync(`${base}.html`, result.html, 'utf8');
  writeFileSync(`${base}.mermaid`, result.mermaid, 'utf8');
  // One-line progress output — keeps `npm run build:examples` informative
  // without leaking the full SVG into the build log.
  process.stdout.write(`[build-examples] ${spec.subdir}: ${result.summary}\n`);
}

async function main(): Promise<void> {
  mkdirSync(EXAMPLES_ROOT, { recursive: true });
  for (const spec of EXAMPLES) {
    await writeExample(spec);
  }
  process.stdout.write(`[build-examples] wrote ${EXAMPLES.length * 3} files under ${EXAMPLES_ROOT}\n`);
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? (err.stack ?? err.message) : String(err);
  process.stderr.write(`[build-examples] fatal: ${msg}\n`);
  process.exit(1);
});
